apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-load-balance
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    run: nginx
  type: LoadBalance
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
